
-- Answer 공개/비공개 + 키워드 답변 (2026-06-12)
ALTER TABLE "Answer" ADD COLUMN IF NOT EXISTS "isPrivate" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Answer" ADD COLUMN IF NOT EXISTS "keywords" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Answer" ADD COLUMN IF NOT EXISTS "aiComposed" BOOLEAN NOT NULL DEFAULT false;
ALTER TYPE "QuestionSource" ADD VALUE IF NOT EXISTS 'custom';
